name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore sampleclasslibrary.sln
      working-directory: sampleclasslibrary
    - name: Build
      run: dotnet build --no-restore
      working-directory: sampleclasslibrary
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: sampleclasslibrary
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@f4c6e4d91ea9785ec823eaeed459042606123402
      uses: SonarSource/sonarcloud-github-action@v1.4
      with:
        # Additional arguments to the sonarcloud scanner
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: sampleclasslibrary # optional, default is .

